TOKYO_BTN: dict[str, str] = {
    # New Tokyo buttons
    'top_all': '🏆Топ',
    'top_10': '🏆10',
    'top_30': '🏆30',
    'top_50': '🏆50',
    'X_top_10': '✅10',
    'X_top_30': '✅30',
    'X_top_50': '✅50',
    'progress': '📈Актив',
    'stats': '🧠Статы',
    'reputation': '🔔Репутация',
    'noobs': '👣Новички',
    'noobs_1': '🕐За сутки',
    'noobs_7': '🕒за 7 дней',
    'noobs_14': '🕘За 14 дней',
    'X_progress': '✅Актив',
    'X_stats': '✅Статы',
    'X_reputation': '✅Репутация',
    'X_noobs': '👣Новички',
    'X_noobs_1': '✅За сутки',
    'X_noobs_7': '✅за 7 дней',
    'X_noobs_14': '✅За 14 дней',
    'dayly': '🏰Дейлики',
    'maps': '🗺Карты',
    'dayly_tokyo': '🏰Токио',
    'dayly_rim': '🏰Рим',
    'dayly_with': '🏰Молот ведьм',
    'X_tokyo': '✅Токио',
    'X_rim': '✅Рим',
    'X_with': '✅Молот ведьм',
    "achievements": "🎖Достижения",
    'story_line': '⭐Сюжет',
    'events': '🎉Ивенты',
    'winners': '🏆Победы',
    'others': '💼Иные',
    'point_guardian': "🛡Щит",
    'X_point_guardian': "✅Щит",
    'maps_sewerage_1': '🗺Канализация 1 этаж',
    'maps_sewerage_2': '🗺Канализация 2 этаж',
    'maps_old_park': '🗺Старый парк',
    'maps_druids_forest': '🗺Лес друидов',
    'maps_dark_lec': '💀Темное поле',
    'X_maps_sewerage_1': '✅Канализация 1 этаж',
    'X_maps_sewerage_2': '✅Канализация 2 этаж',
    'X_maps_old_park': '✅Старый парк',
    'X_maps_druids_forest': '✅Лес друидов',
    'X_maps_dark_lec': '✅Темное поле',
}

TOKYO_MEDIA: dict[str, str] = {
    'dayly_tokyo': 'AgACAgIAAxkBAAIPRWWA86CxsPXblsSptx12sHyNvnV-AAJB0jEbNDAISF99wPoT9X2_AQADAgADeQADMwQ',
    'dayly_rim': 'AgACAgIAAxkBAAIPR2WA87Ez0Mb9ZejhPm9v69PG1ij3AAJC0jEbNDAISIPlFqIB3QXlAQADAgADeQADMwQ',
    'dayly_with': 'AgACAgIAAxkBAAITSWXH6Kbsgeerw7g3NngSiezwdVpEAAJR3DEb81xASvMKgbMOW-ZHAQADAgADeQADNAQ',
    'dayly_2024': 'AgACAgIAAxkBAAIQaWWKilw0LsvqLRxWpIkCnsUbE0dvAAID0TEbYydZSCnjyZHF2nnqAQADAgADeQADMwQ',
    'photo_sewerage_1': 'AgACAgIAAxkBAAIP4GWHFDJHdpM67xPn8Zj02BvR0GjnAAIq0jEbrKk5SIshTLvxMK5jAQADAgADeQADMwQ',
    'photo_sewerage_2': 'AgACAgIAAxkBAAIQAAFlhysdLJVv5FddLy-_MmonLh-5twACztIxG6ypOUixAhlart_u5wEAAwIAA3kAAzME',
    'photo_old_park': 'AgACAgIAAxkBAAIQCWWHQwAB_PsCCAAB-Kh3zkpMLqJyoRMAAsLYMRsfezhIIa-sdFw4dTkBAAMCAAN5AAMzBA',
    'photo_druids_forest': 'AgACAgIAAxkBAAIQpGWMdBEt4C-QOMrKY79fJLOR-LxMAAJp2DEb3c5hSFlv8LQNUECAAQADAgADeQADMwQ',
    'photo_dark_lec': 'AgACAgIAAxkBAAIUaGXf0X6SLmxd8KnayhXaFjA5mRIXAAIW1TEbXFkAAUtaParqkU2c3gEAAwIAA3kAAzQE',
    'NT_Logo': "AgACAgIAAxkBAAIRgmWayn6bHemibt0IDeW-nzFGYENXAAJM1TEbWKHYSHw_M2O_8IwmAQADAgADeQADNAQ"
}
